alter table if exists order drop foreign key if exists FK3b51sphq5i3qy7iai0o5lmu7l;
alter table if exists order drop foreign key if exists FKt7abetueht6dd1gs9jyl3o4t7;
alter table if exists product drop foreign key if exists FKs6cydsualtsrprvlf2bb3lcam;
alter table if exists product drop foreign key if exists FK1mtsbur82frn64de7balymq9s;
alter table if exists review drop foreign key if exists FKiyof1sindb9qiqr9o8npj8klt;
alter table if exists review drop foreign key if exists FKiyf57dy48lyiftdrf7y87rnxi;
drop table if exists brand;
drop table if exists category;
drop table if exists order;
drop table if exists product;
drop table if exists review;
drop table if exists user;
